version: "3.9"

services:
  pg_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=d_db1
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=353062
    volumes:
      - db:/var/lib/postgresql/data postgres
    ports:
    - "5433:5432"

volumes:
  db: